function results = calculateROC(fig_number, results,sampling,scanner,tissue,simulation)


for i = 1:sampling.number
    for j = 1:scanner.number
        switch fig_number
            case 2
                % E1.1
                [results.ROC.E1_1.IVIM.sNLLS.f.(sampling.name{i}).(scanner.name{j}).x,...
                    results.ROC.E1_1.IVIM.sNLLS.f.(sampling.name{i}).(scanner.name{j}).y,...
                    ~,results.ROC.E1_1.IVIM.sNLLS.f.(sampling.name{i}).(scanner.name{j}).AUC] = ...
                    perfcurve(...
                    [ones(simulation.(tissue.name{2}).number,1); zeros(simulation.(tissue.name{3}).number,1)],...
                    [results.(tissue.name{2}).(sampling.name{i}).(scanner.name{i}).IVIM.sNLLS.parameters(2,:),...
                    results.(tissue.name{3}).(sampling.name{i}).(scanner.name{i}).IVIM.sNLLS.parameters(2,:)],1);
                
                [results.ROC.E1_1.IVIM.sNLLS.Dslow.(sampling.name{i}).(scanner.name{j}).x,...
                    results.ROC.E1_1.IVIM.sNLLS.Dslow.(sampling.name{i}).(scanner.name{j}).y,...
                    ~,results.ROC.E1_1.IVIM.sNLLS.Dslow.(sampling.name{i}).(scanner.name{j}).AUC] = ...
                    perfcurve(...
                    [ones(simulation.(tissue.name{2}).number,1); zeros(simulation.(tissue.name{3}).number,1)],...
                    [results.(tissue.name{2}).(sampling.name{i}).(scanner.name{i}).IVIM.sNLLS.parameters(3,:),...
                    results.(tissue.name{3}).(sampling.name{i}).(scanner.name{i}).IVIM.sNLLS.parameters(3,:)],1);
                
                [results.ROC.E1_1.IVIM.sNLLS.Dfast.(sampling.name{i}).(scanner.name{j}).x,...
                    results.ROC.E1_1.IVIM.sNLLS.Dfast.(sampling.name{i}).(scanner.name{j}).y,...
                    ~,results.ROC.E1_1.IVIM.sNLLS.Dfast.(sampling.name{i}).(scanner.name{j}).AUC] = ...
                    perfcurve(...
                    [ones(simulation.(tissue.name{2}).number,1); zeros(simulation.(tissue.name{3}).number,1)],...
                    [results.(tissue.name{2}).(sampling.name{i}).(scanner.name{i}).IVIM.sNLLS.parameters(4,:),...
                    results.(tissue.name{3}).(sampling.name{i}).(scanner.name{i}).IVIM.sNLLS.parameters(4,:)],1);
                
                % E1.2
                [results.ROC.E1_2.IVIM.sNLLS.f.(sampling.name{i}).(scanner.name{j}).x,...
                    results.ROC.E1_2.IVIM.sNLLS.f.(sampling.name{i}).(scanner.name{j}).y,...
                    ~,results.ROC.E1_2.IVIM.sNLLS.f.(sampling.name{i}).(scanner.name{j}).AUC] = ...
                    perfcurve(...
                    [ones(simulation.(tissue.name{1}).number,1); zeros(simulation.(tissue.name{2}).number,1)],...
                    [results.(tissue.name{1}).(sampling.name{i}).(scanner.name{i}).IVIM.sNLLS.parameters(2,:),...
                    results.(tissue.name{2}).(sampling.name{i}).(scanner.name{i}).IVIM.sNLLS.parameters(2,:)],0);
                
                [results.ROC.E1_2.IVIM.sNLLS.Dslow.(sampling.name{i}).(scanner.name{j}).x,...
                    results.ROC.E1_2.IVIM.sNLLS.Dslow.(sampling.name{i}).(scanner.name{j}).y,...
                    ~,results.ROC.E1_2.IVIM.sNLLS.Dslow.(sampling.name{i}).(scanner.name{j}).AUC] = ...
                    perfcurve(...
                    [ones(simulation.(tissue.name{1}).number,1); zeros(simulation.(tissue.name{2}).number,1)],...
                    [results.(tissue.name{1}).(sampling.name{i}).(scanner.name{i}).IVIM.sNLLS.parameters(3,:),...
                    results.(tissue.name{2}).(sampling.name{i}).(scanner.name{i}).IVIM.sNLLS.parameters(3,:)],1);
                
                [results.ROC.E1_2.IVIM.sNLLS.Dfast.(sampling.name{i}).(scanner.name{j}).x,...
                    results.ROC.E1_2.IVIM.sNLLS.Dfast.(sampling.name{i}).(scanner.name{j}).y,...
                    ~,results.ROC.E1_2.IVIM.sNLLS.Dfast.(sampling.name{i}).(scanner.name{j}).AUC] = ...
                    perfcurve(...
                    [ones(simulation.(tissue.name{1}).number,1); zeros(simulation.(tissue.name{2}).number,1)],...
                    [results.(tissue.name{1}).(sampling.name{i}).(scanner.name{i}).IVIM.sNLLS.parameters(4,:),...
                    results.(tissue.name{2}).(sampling.name{i}).(scanner.name{i}).IVIM.sNLLS.parameters(4,:)],0);
                
                % E1.3
                [results.ROC.E1_3.IVIM.sNLLS.f.(sampling.name{i}).(scanner.name{j}).x,...
                    results.ROC.E1_3.IVIM.sNLLS.f.(sampling.name{i}).(scanner.name{j}).y,...
                    ~,results.ROC.E1_3.IVIM.sNLLS.f.(sampling.name{i}).(scanner.name{j}).AUC] = ...
                    perfcurve(...
                    [ones(simulation.(tissue.name{1}).number,1); zeros(simulation.(tissue.name{3}).number,1)],...
                    [results.(tissue.name{1}).(sampling.name{i}).(scanner.name{i}).IVIM.sNLLS.parameters(2,:),...
                    results.(tissue.name{3}).(sampling.name{i}).(scanner.name{i}).IVIM.sNLLS.parameters(2,:)],1);
                
                [results.ROC.E1_3.IVIM.sNLLS.Dslow.(sampling.name{i}).(scanner.name{j}).x,...
                    results.ROC.E1_3.IVIM.sNLLS.Dslow.(sampling.name{i}).(scanner.name{j}).y,...
                    ~,results.ROC.E1_3.IVIM.sNLLS.Dslow.(sampling.name{i}).(scanner.name{j}).AUC] = ...
                    perfcurve(...
                    [ones(simulation.(tissue.name{1}).number,1); zeros(simulation.(tissue.name{3}).number,1)],...
                    [results.(tissue.name{1}).(sampling.name{i}).(scanner.name{i}).IVIM.sNLLS.parameters(3,:),...
                    results.(tissue.name{3}).(sampling.name{i}).(scanner.name{i}).IVIM.sNLLS.parameters(3,:)],1);
                
                [results.ROC.E1_3.IVIM.sNLLS.Dfast.(sampling.name{i}).(scanner.name{j}).x,...
                    results.ROC.E1_3.IVIM.sNLLS.Dfast.(sampling.name{i}).(scanner.name{j}).y,...
                    ~,results.ROC.E1_3.IVIM.sNLLS.Dfast.(sampling.name{i}).(scanner.name{j}).AUC] = ...
                    perfcurve(...
                    [ones(simulation.(tissue.name{1}).number,1); zeros(simulation.(tissue.name{3}).number,1)],...
                    [results.(tissue.name{1}).(sampling.name{i}).(scanner.name{i}).IVIM.sNLLS.parameters(4,:),...
                    results.(tissue.name{3}).(sampling.name{i}).(scanner.name{i}).IVIM.sNLLS.parameters(4,:)],1);
                
                % subsampling
                rng(6345123)
                n_samples = 10000;
                active_size = 25;
                chronic_size = 22;
                control_size = 21;
                
                results.ROC.E1_1.subsample.AUC = NaN(n_samples,3);
                results.ROC.E1_2.subsample.AUC = NaN(n_samples,3);
                results.ROC.E1_3.subsample.AUC = NaN(n_samples,3);
                
                for k = 1:n_samples
                    active_subsample = datasample(...
                        results.(tissue.name{1}).(sampling.name{i}).(scanner.name{j}).IVIM.sNLLS.parameters(2:end,:),...
                        active_size,...
                        2,...
                        'Replace',false);
                    chronic_subsample = datasample(...
                        results.(tissue.name{2}).(sampling.name{i}).(scanner.name{j}).IVIM.sNLLS.parameters(2:end,:),...
                        chronic_size,...
                        2,...
                        'Replace',false);
                    control_subsample = datasample(...
                        results.(tissue.name{3}).(sampling.name{i}).(scanner.name{j}).IVIM.sNLLS.parameters(2:end,:),...
                        control_size,...
                        2,...
                        'Replace',false);
                    
                    % parameters
                    for l = 1:3
                        [~,~,~,results.ROC.E1_1.subsample.AUC(k,l)] = perfcurve(...
                            [ones(chronic_size,1); zeros(control_size,1)],...
                            [chronic_subsample(l,:)';...
                            control_subsample(l,:)'],1);
                        [~,~,~,results.ROC.E1_2.subsample.AUC(k,l)] = perfcurve(...
                            [ones(active_size,1); zeros(chronic_size,1)],...
                            [active_subsample(l,:)';...
                            chronic_subsample(l,:)'],1);
                        [~,~,~,results.ROC.E1_3.subsample.AUC(k,l)] = perfcurve(...
                            [ones(active_size,1); zeros(control_size,1)],...
                            [active_subsample(l,:)';...
                            control_subsample(l,:)'],1);
                        
                    end
                end
                
            case 3
                
                % E1.4
                [results.ROC.E1_4.IVIM.bcNLLS.Dslow.(sampling.name{i}).(scanner.name{j}).x,...
                    results.ROC.E1_4.IVIM.bcNLLS.Dslow.(sampling.name{i}).(scanner.name{j}).y,...
                    ~,results.ROC.E1_4.IVIM.bcNLLS.Dslow.(sampling.name{i}).(scanner.name{j}).AUC] = ...
                    perfcurve(...
                    [ones(simulation.(tissue.name{1}).number,1); zeros(simulation.(tissue.name{2}).number,1)],...
                    [results.(tissue.name{1}).(sampling.name{i}).(scanner.name{j}).IVIM.bcNLLS.parameters(3,:),...
                    results.(tissue.name{2}).(sampling.name{i}).(scanner.name{j}).IVIM.bcNLLS.parameters(3,:)],1);
                
                [results.ROC.E1_4.ADC.wLS.ADC.(sampling.name{i}).(scanner.name{j}).x,...
                    results.ROC.E1_4.ADC.wLS.ADC.(sampling.name{i}).(scanner.name{j}).y,...
                    ~,results.ROC.E1_4.ADC.wLS.ADC.(sampling.name{i}).(scanner.name{j}).AUC] = ...
                    perfcurve(...
                    [ones(simulation.(tissue.name{1}).number,1); zeros(simulation.(tissue.name{2}).number,1)],...
                    [results.(tissue.name{1}).(sampling.name{i}).(scanner.name{j}).ADC.wLS.parameters(2,:),...
                    results.(tissue.name{2}).(sampling.name{i}).(scanner.name{j}).ADC.wLS.parameters(2,:)],1);
                
                % subsampling
                rng(6345123)
                n_samples = 10000;
                inflamed_size = 11;
                control_size = 17;
                
                for k = 1:n_samples
                    inflamed_subsample_IVIM = datasample(...
                        results.(tissue.name{1}).(sampling.name{i}).(scanner.name{j}).IVIM.bcNLLS.parameters(3,:),...
                        inflamed_size,...
                        2,...
                        'Replace',false);
                    control_subsample_IVIM = datasample(...
                        results.(tissue.name{2}).(sampling.name{i}).(scanner.name{j}).IVIM.bcNLLS.parameters(3,:),...
                        control_size,...
                        2,...
                        'Replace',false);
                    
                    inflamed_subsample_ADC = datasample(...
                        results.(tissue.name{1}).(sampling.name{i}).(scanner.name{j}).ADC.wLS.parameters(2,:),...
                        inflamed_size,...
                        2,...
                        'Replace',false);
                    control_subsample_ADC = datasample(...
                        results.(tissue.name{2}).(sampling.name{i}).(scanner.name{j}).ADC.wLS.parameters(2,:),...
                        control_size,...
                        2,...
                        'Replace',false);
                    
                    [~,~,~,results.ROC.E1_4.subsample.ADC.AUC(k)] = perfcurve(...
                        [ones(inflamed_size,1); zeros(control_size,1)],...
                        [inflamed_subsample_ADC';...
                        control_subsample_ADC'],1);
                    [~,~,~,results.ROC.E1_4.subsample.IVIM.AUC(k)] = perfcurve(...
                        [ones(inflamed_size,1); zeros(control_size,1)],...
                        [inflamed_subsample_IVIM';...
                        control_subsample_IVIM'],1);
                end
                
                % import experimental ROC data
                load E1_4_ROC.mat
                results.ROC.E1_4.ADC.wLS.ADC.Clinical.x = E1_4_ROC.ADC.x;
                results.ROC.E1_4.ADC.wLS.ADC.Clinical.y = E1_4_ROC.ADC.y;
                results.ROC.E1_4.ADC.wLS.ADC.Clinical.AUC = E1_4_ROC.ADC.AUC;
                
                results.ROC.E1_4.IVIM.bcNLLS.Dslow.Clinical.x = E1_4_ROC.IVIM.bcNLLS.Dt.x;
                results.ROC.E1_4.IVIM.bcNLLS.Dslow.Clinical.y = E1_4_ROC.IVIM.bcNLLS.Dt.y;
                results.ROC.E1_4.IVIM.bcNLLS.Dslow.Clinical.AUC = E1_4_ROC.IVIM.bcNLLS.Dt.AUC;
                
            case {4,5}
                % E2.1 ROC
                [results.ROC.E2_1.IVIM.sNLLS.f.(sampling.name{i}).(scanner.name{j}).x,...
                    results.ROC.E2_1.IVIM.sNLLS.f.(sampling.name{i}).(scanner.name{j}).y,...
                    ~,results.ROC.E2_1.IVIM.sNLLS.f.(sampling.name{i}).(scanner.name{j}).AUC] = ...
                    perfcurve(...
                    [ones(simulation.(tissue.name{1}).number,1); zeros(simulation.(tissue.name{2}).number,1)],...
                    [results.(tissue.name{1}).(sampling.name{i}).(scanner.name{i}).IVIM.sNLLS.parameters(2,:),...
                    results.(tissue.name{2}).(sampling.name{i}).(scanner.name{i}).IVIM.sNLLS.parameters(2,:)],0);
                
                [results.ROC.E2_1.IVIM.bcNLLS.f.(sampling.name{i}).(scanner.name{j}).x,...
                    results.ROC.E2_1.IVIM.bcNLLS.f.(sampling.name{i}).(scanner.name{j}).y,...
                    ~,results.ROC.E2_1.IVIM.bcNLLS.f.(sampling.name{i}).(scanner.name{j}).AUC] = ...
                    perfcurve(...
                    [ones(simulation.(tissue.name{1}).number,1); zeros(simulation.(tissue.name{2}).number,1)],...
                    [results.(tissue.name{1}).(sampling.name{i}).(scanner.name{j}).IVIM.bcNLLS.parameters(2,:),...
                    results.(tissue.name{2}).(sampling.name{i}).(scanner.name{j}).IVIM.bcNLLS.parameters(2,:)],0);
                
                [results.ROC.E2_1.ADC.wLS.ADC.(sampling.name{i}).(scanner.name{j}).x,...
                    results.ROC.E2_1.ADC.wLS.ADC.(sampling.name{i}).(scanner.name{j}).y,...
                    ~,results.ROC.E2_1.ADC.wLS.ADC.(sampling.name{i}).(scanner.name{j}).AUC] = ...
                    perfcurve(...
                    [ones(simulation.(tissue.name{1}).number,1); zeros(simulation.(tissue.name{2}).number,1)],...
                    [results.(tissue.name{1}).(sampling.name{i}).(scanner.name{j}).ADC.wLS.parameters(2,:),...
                    results.(tissue.name{2}).(sampling.name{i}).(scanner.name{j}).ADC.wLS.parameters(2,:)],0);
                
                %E2.1 CNR
                results.CNR.E2_1.ADC.wLS.ADC.delta_mu = abs(mean(results.Healthy.Nine.Synthetic.ADC.wLS.parameters(2,:))...
                    - mean(results.Chronic_1.Nine.Synthetic.ADC.wLS.parameters(2,:)));
                results.CNR.E2_1.ADC.wLS.ADC.sigma.Healthy = std(results.Healthy.Nine.Synthetic.ADC.wLS.parameters(2,:));
                results.CNR.E2_1.ADC.wLS.ADC.sigma.Chronic_1 = std(results.Chronic_1.Nine.Synthetic.ADC.wLS.parameters(2,:));
                results.CNR.E2_1.ADC.wLS.ADC.CNR = results.CNR.E2_1.ADC.wLS.ADC.delta_mu / ...
                    mean([results.CNR.E2_1.ADC.wLS.ADC.sigma.Healthy, results.CNR.E2_1.ADC.wLS.ADC.sigma.Chronic_1]);
                
                results.CNR.E2_1.IVIM.sNLLS.f.delta_mu = abs(mean(results.Healthy.Nine.Synthetic.IVIM.sNLLS.parameters(2,:)...
                    - mean(results.Chronic_1.Nine.Synthetic.IVIM.sNLLS.parameters(2,:))));
                results.CNR.E2_1.IVIM.sNLLS.f.sigma.Healthy = std(results.Healthy.Nine.Synthetic.IVIM.sNLLS.parameters(2,:));
                results.CNR.E2_1.IVIM.sNLLS.f.sigma.Chronic_1 = std(results.Chronic_1.Nine.Synthetic.IVIM.sNLLS.parameters(2,:));
                results.CNR.E2_1.IVIM.sNLLS.f.CNR = results.CNR.E2_1.IVIM.sNLLS.f.delta_mu / ...
                    mean([results.CNR.E2_1.IVIM.sNLLS.f.sigma.Healthy, results.CNR.E2_1.IVIM.sNLLS.f.sigma.Chronic_1]);
                
                results.CNR.E2_1.IVIM.bcNLLS.f.delta_mu = abs(mean(results.Healthy.Nine.Synthetic.IVIM.bcNLLS.parameters(2,:)...
                    - mean(results.Chronic_1.Nine.Synthetic.IVIM.bcNLLS.parameters(2,:))));
                results.CNR.E2_1.IVIM.bcNLLS.f.sigma.Healthy = std(results.Healthy.Nine.Synthetic.IVIM.bcNLLS.parameters(2,:));
                results.CNR.E2_1.IVIM.bcNLLS.f.sigma.Chronic_1 = std(results.Chronic_1.Nine.Synthetic.IVIM.bcNLLS.parameters(2,:));
                results.CNR.E2_1.IVIM.bcNLLS.f.CNR = results.CNR.E2_1.IVIM.bcNLLS.f.delta_mu / ...
                    mean([results.CNR.E2_1.IVIM.bcNLLS.f.sigma.Healthy, results.CNR.E2_1.IVIM.bcNLLS.f.sigma.Chronic_1]);
                
                
                % E2.2 ROC
                [results.ROC.E2_2.IVIM.sNLLS.Dslow.(sampling.name{i}).(scanner.name{j}).x,...
                    results.ROC.E2_2.IVIM.sNLLS.Dslow.(sampling.name{i}).(scanner.name{j}).y,...
                    ~,results.ROC.E2_2.IVIM.sNLLS.Dslow.(sampling.name{i}).(scanner.name{j}).AUC] = ...
                    perfcurve(...
                    [ones(simulation.(tissue.name{3}).number,1); zeros(simulation.(tissue.name{4}).number,1)],...
                    [results.(tissue.name{3}).(sampling.name{i}).(scanner.name{i}).IVIM.sNLLS.parameters(3,:),...
                    results.(tissue.name{4}).(sampling.name{i}).(scanner.name{i}).IVIM.sNLLS.parameters(3,:)],1);
                
                [results.ROC.E2_2.IVIM.bcNLLS.Dslow.(sampling.name{i}).(scanner.name{j}).x,...
                    results.ROC.E2_2.IVIM.bcNLLS.Dslow.(sampling.name{i}).(scanner.name{j}).y,...
                    ~,results.ROC.E2_2.IVIM.bcNLLS.Dslow.(sampling.name{i}).(scanner.name{j}).AUC] = ...
                    perfcurve(...
                    [ones(simulation.(tissue.name{3}).number,1); zeros(simulation.(tissue.name{4}).number,1)],...
                    [results.(tissue.name{3}).(sampling.name{i}).(scanner.name{j}).IVIM.bcNLLS.parameters(3,:),...
                    results.(tissue.name{4}).(sampling.name{i}).(scanner.name{j}).IVIM.bcNLLS.parameters(3,:)],1);
                
                [results.ROC.E2_2.ADC.wLS.ADC.(sampling.name{i}).(scanner.name{j}).x,...
                    results.ROC.E2_2.ADC.wLS.ADC.(sampling.name{i}).(scanner.name{j}).y,...
                    ~,results.ROC.E2_2.ADC.wLS.ADC.(sampling.name{i}).(scanner.name{j}).AUC] = ...
                    perfcurve(...
                    [ones(simulation.(tissue.name{3}).number,1); zeros(simulation.(tissue.name{4}).number,1)],...
                    [results.(tissue.name{3}).(sampling.name{i}).(scanner.name{j}).ADC.wLS.parameters(2,:),...
                    results.(tissue.name{4}).(sampling.name{i}).(scanner.name{j}).ADC.wLS.parameters(2,:)],1);
                
                %E2.2 CNR
                results.CNR.E2_2.ADC.wLS.ADC.delta_mu = abs(mean(results.Active.Nine.Synthetic.ADC.wLS.parameters(2,:))...
                    - mean(results.Chronic_2.Nine.Synthetic.ADC.wLS.parameters(2,:)));
                results.CNR.E2_2.ADC.wLS.ADC.sigma.Active = std(results.Active.Nine.Synthetic.ADC.wLS.parameters(2,:));
                results.CNR.E2_2.ADC.wLS.ADC.sigma.Chronic_2 = std(results.Chronic_2.Nine.Synthetic.ADC.wLS.parameters(2,:));
                results.CNR.E2_2.ADC.wLS.ADC.CNR = results.CNR.E2_2.ADC.wLS.ADC.delta_mu / ...
                    mean([results.CNR.E2_2.ADC.wLS.ADC.sigma.Active, results.CNR.E2_2.ADC.wLS.ADC.sigma.Chronic_2]);
                
                results.CNR.E2_2.IVIM.sNLLS.Dslow.delta_mu = abs(mean(results.Active.Nine.Synthetic.IVIM.sNLLS.parameters(3,:)...
                    - mean(results.Chronic_2.Nine.Synthetic.IVIM.sNLLS.parameters(3,:))));
                results.CNR.E2_2.IVIM.sNLLS.Dslow.sigma.Active = std(results.Healthy.Nine.Synthetic.IVIM.sNLLS.parameters(3,:));
                results.CNR.E2_2.IVIM.sNLLS.Dslow.sigma.Chronic_2 = std(results.Chronic_1.Nine.Synthetic.IVIM.sNLLS.parameters(3,:));
                results.CNR.E2_2.IVIM.sNLLS.Dslow.CNR = results.CNR.E2_2.IVIM.sNLLS.Dslow.delta_mu / ...
                    mean([results.CNR.E2_2.IVIM.sNLLS.Dslow.sigma.Active, results.CNR.E2_2.IVIM.sNLLS.Dslow.sigma.Chronic_2]);
                
                results.CNR.E2_2.IVIM.bcNLLS.Dslow.delta_mu = abs(mean(results.Active.Nine.Synthetic.IVIM.bcNLLS.parameters(3,:)...
                    - mean(results.Chronic_2.Nine.Synthetic.IVIM.bcNLLS.parameters(3,:))));
                results.CNR.E2_2.IVIM.bcNLLS.Dslow.sigma.Active = std(results.Healthy.Nine.Synthetic.IVIM.bcNLLS.parameters(3,:));
                results.CNR.E2_2.IVIM.bcNLLS.Dslow.sigma.Chronic_2 = std(results.Chronic_1.Nine.Synthetic.IVIM.bcNLLS.parameters(3,:));
                results.CNR.E2_2.IVIM.bcNLLS.Dslow.CNR = results.CNR.E2_2.IVIM.bcNLLS.Dslow.delta_mu / ...
                    mean([results.CNR.E2_2.IVIM.bcNLLS.Dslow.sigma.Active, results.CNR.E2_2.IVIM.bcNLLS.Dslow.sigma.Chronic_2]);
                
        end
    end
    
    
end
