function plotFigures(fig_number, tissue, sampling, scanner, results, simulation, data)

adc_colour = [255 128 31]/255;
bcnlls_colour = [45 200 187]/255;
snlls_colour = [102 0 204]/255;

f_colour = [216 179 11]/255;
Dt_colour = [128 33 13]/255;
Dp_colour = [13 124 21]/255;
ADC_colour = [13, 128, 94]/255;

% plotting linestyles
f_style = '--';
Dt_style = '-';
Dp_style = ':';
adc_style = '-.';

switch fig_number
    
    case 2
        close all
        % spacing between subplots
        spacing = 0.05;
        
        % generate square figure
        figure('units','pixels','outerposition',[0 0 990 990])
        
        % roc linewidth
        linewidth_ROC = 2.5;
        
        %histogram linewidth
        linewidth_hist = 2.5;
        
        % panel label options
        rect_position = [0.02 0.02 0.1 0.1];
        rect_width = 1.5;
        text_position = [0.03,0.06];
        text_size = 18;
        label_size = 12;
        
        % E1.1 simulated ROC curves
        subaxis(3,3,1,'Spacing',spacing)
        % Dslow ROC plot
        plot(results.ROC.E1_1.IVIM.sNLLS.Dslow.Ten.Adjusted.x,...
            results.ROC.E1_1.IVIM.sNLLS.Dslow.Ten.Adjusted.y,...
            'Color',Dt_colour,'LineWidth',linewidth_ROC,'LineStyle',Dt_style)
        hold on
        % f ROC plot
        plot(results.ROC.E1_1.IVIM.sNLLS.f.Ten.Adjusted.x,...
            results.ROC.E1_1.IVIM.sNLLS.f.Ten.Adjusted.y,...
            'Color',f_colour,'LineWidth',linewidth_ROC,'LineStyle',f_style)
        % Dfast ROC plot
        plot(results.ROC.E1_1.IVIM.sNLLS.Dfast.Ten.Adjusted.x,...
            results.ROC.E1_1.IVIM.sNLLS.Dfast.Ten.Adjusted.y,...
            'Color',Dp_colour,'LineWidth',linewidth_ROC,'LineStyle',Dp_style)
        % x = y line
        fplot(@(x) x,[0 1],'k','LineWidth',linewidth_ROC/2)
        % annotation showing AUC values
        text(0.45,0.18,sprintf('AUC_{D_{slow}} = %.3f \nAUC_{f} = %.3f \nAUC_{D_{fast}} = %.3f',...
            results.ROC.E1_1.IVIM.sNLLS.Dslow.Ten.Adjusted.AUC  ,...
            results.ROC.E1_1.IVIM.sNLLS.f.Ten.Adjusted.AUC  ,...
            results.ROC.E1_1.IVIM.sNLLS.Dfast.Ten.Adjusted.AUC  ),'FontSize',12)
        % set axis settings
        axis equal
        xlim([0 1])
        ylim([0 1])
        xlabel('False positive rate','Interpreter','Latex','Units','normalized','FontSize',label_size)
        ylabel(['\fontsize{15}{0}\selectfont \textbf{E1.1 - Chronic vs Healthy}', char(10), ...
            char(10), ...
       '\fontsize{12}{0}\selectfont True positive rate'], ...
       'interpreter','latex','Units','normalized')
        % legend
        legend('$D_{slow}$','$f$','$D_{fast}$',...
            'Position',[0.252,0.752,0.055,0.055],...
            'Interpreter','Latex','FontSize',11)
        text(text_position(1),text_position(2),'\textbf{A}','Units','normalized','FontSize',text_size,'Interpreter','Latex')
        rectangle('Position',rect_position,'LineWidth',rect_width,'FaceColor','w')
        
        % simulated ROC curves - task 2
        subaxis(3,3,4,'Spacing',spacing)
        % Dslow ROC plot
        plot(results.ROC.E1_2.IVIM.sNLLS.Dslow.Ten.Adjusted.x,...
            results.ROC.E1_2.IVIM.sNLLS.Dslow.Ten.Adjusted.y,...
            'Color',Dt_colour,'LineWidth',linewidth_ROC,'LineStyle',Dt_style)
        hold on
        % f ROC plot
        plot(results.ROC.E1_2.IVIM.sNLLS.f.Ten.Adjusted.x,...
            results.ROC.E1_2.IVIM.sNLLS.f.Ten.Adjusted.y,...
            'Color',f_colour,'LineWidth',linewidth_ROC,'LineStyle',f_style)
        % Dfast ROC plot
        plot(results.ROC.E1_2.IVIM.sNLLS.Dfast.Ten.Adjusted.x,...
            results.ROC.E1_2.IVIM.sNLLS.Dfast.Ten.Adjusted.y,...
            'Color',Dp_colour,'LineWidth',linewidth_ROC,'LineStyle',Dp_style)
        % x = y line
        fplot(@(x) x,[0 1],'k','LineWidth',linewidth_ROC/2)
        % annotation showing AUC values
        text(0.45,0.18,sprintf('AUC_{D_{slow}} = %.3f \nAUC_{f} = %.3f \nAUC_{D_{fast}} = %.3f',...
            results.ROC.E1_2.IVIM.sNLLS.Dslow.Ten.Adjusted.AUC,...
            results.ROC.E1_2.IVIM.sNLLS.f.Ten.Adjusted.AUC,...
            results.ROC.E1_2.IVIM.sNLLS.Dfast.Ten.Adjusted.AUC),'FontSize',12)
        % set axis settings
        axis equal
        xlim([0 1])
        ylim([0 1])
        xlabel('False positive rate','Interpreter','Latex','Units','normalized','FontSize',label_size)
        ylabel(['\fontsize{15}{0}\selectfont \textbf{E1.2 - Active vs Chronic}', char(10), ...
            char(10), ...
       '\fontsize{12}{0}\selectfont True positive rate'], ...
       'interpreter','latex','Units','normalized')
        % legend
        legend('$D_{slow}$','$f$','$D_{fast}$',...
            'Position',[0.252,0.469,0.055,0.055],...
            'Interpreter','Latex','FontSize',11)
        text(text_position(1),text_position(2),'\textbf{D}','Units','normalized','FontSize',text_size,'Interpreter','Latex')
        rectangle('Position',rect_position,'LineWidth',rect_width,'FaceColor','w')
        
        % simulated ROC curves - task 3
        subaxis(3,3,7,'Spacing',spacing)
        % Dslow ROC plot
        plot(results.ROC.E1_3.IVIM.sNLLS.Dslow.Ten.Adjusted.x,...
            results.ROC.E1_3.IVIM.sNLLS.Dslow.Ten.Adjusted.y,...
            'Color',Dt_colour,'LineWidth',linewidth_ROC,'LineStyle',Dt_style)
        hold on
        % f ROC plot
        plot(results.ROC.E1_3.IVIM.sNLLS.f.Ten.Adjusted.x,...
            results.ROC.E1_3.IVIM.sNLLS.f.Ten.Adjusted.y,...
            'Color',f_colour,'LineWidth',linewidth_ROC,'LineStyle',f_style)
        
        % Dfast ROC plot
        plot(results.ROC.E1_3.IVIM.sNLLS.Dfast.Ten.Adjusted.x,...
            results.ROC.E1_3.IVIM.sNLLS.Dfast.Ten.Adjusted.y,...
            'Color',Dp_colour,'LineWidth',linewidth_ROC,'LineStyle',Dp_style)
        % x = y line
        fplot(@(x) x,[0 1],'k','LineWidth',linewidth_ROC/2)
        % annotation showing AUC values
        text(0.45,0.18,sprintf('AUC_{D_{slow}} = %.3f \nAUC_{f} = %.3f \nAUC_{D_{fast}} = %.3f',...
            results.ROC.E1_3.IVIM.sNLLS.Dslow.Ten.Adjusted.AUC,...
            results.ROC.E1_3.IVIM.sNLLS.f.Ten.Adjusted.AUC,...
            results.ROC.E1_3.IVIM.sNLLS.Dfast.Ten.Adjusted.AUC),'FontSize',12)
        % set axis settings
        axis equal
        xlim([0 1])
        ylim([0 1])
        xlabel('False positive rate','Interpreter','Latex','Units','normalized','FontSize',label_size)
        ylabel(['\fontsize{15}{0}\selectfont \textbf{E1.3 - Active vs Healthy}', char(10), ...
            char(10), ...
       '\fontsize{12}{0}\selectfont True positive rate'], ...
       'interpreter','latex','Units','normalized')
        % legend
        legend('$D_{slow}$','$f$','$D_{fast}$',...
            'Position',[0.252,0.185,0.055,0.055],...
            'Interpreter','Latex','FontSize',11)
        text(text_position(1),text_position(2),'\textbf{G}','Units','normalized','FontSize',text_size,'Interpreter','Latex')
        rectangle('Position',rect_position,'LineWidth',rect_width,'FaceColor','w')
        
        % Zhao ROC E1_1
        subaxis(3,3,2,'Spacing',spacing)
        image(imread('fig7_cropped.jpg'))
        axis image;
        ax = gca;
        ax.XRuler.Axle.Visible = 'off';
        ax.YRuler.Axle.Visible = 'off';
        set(ax,'box','off')
        xl = xlim;
        yl = ylim;
        xticks([0.030 0.218 0.404 0.597 0.783 0.971]*xl(2))
        xticklabels({'0','0.2','0.4','0.6','0.8','1'})
        yticks([0.030 0.218 0.404 0.597 0.783 0.971]*yl(2))
        yticklabels({'1','0.8','0.6','0.4','0.2','0'})
        xlabel('False positive rate','Interpreter','Latex','FontSize',label_size)
        ylabel('True positive rate','Interpreter','Latex','FontSize',label_size)
        xl = xlim;
        yl = ylim;
        rect_position_inverse = rect_position.*[xl(2),yl(2),xl(2),yl(2)];
        rect_position_inverse(2) = yl(2)-rect_position_inverse(2)-rect_position(4)*yl(2);
        text(text_position(1),text_position(2),'\textbf{B}','Units','normalized','FontSize',text_size,'Interpreter','Latex')
        rectangle('Position',rect_position_inverse,'LineWidth',rect_width,'FaceColor','w')
        
        % Zhao ROC E1_2
        subaxis(3,3,5,'Spacing',spacing)
        image(imread('fig6_cropped.jpg'))
        axis image;
        ax = gca;
        ax.XRuler.Axle.Visible = 'off';
        ax.YRuler.Axle.Visible = 'off';
        set(ax,'box','off')
        xl = xlim;
        yl = ylim;
        xticks([0.030 0.218 0.404 0.597 0.783 0.971]*xl(2))
        xticklabels({'0','0.2','0.4','0.6','0.8','1'})
        yticks([0.030 0.218 0.404 0.597 0.783 0.971]*yl(2))
        yticklabels({'1','0.8','0.6','0.4','0.2','0'})
        xlabel('False positive rate','Interpreter','Latex','Units','normalized','FontSize',label_size)
        ylabel('True positive rate','Interpreter','Latex','Units','normalized','FontSize',label_size)
        xl = xlim;
        yl = ylim;
        rect_position_inverse = rect_position.*[xl(2),yl(2),xl(2),yl(2)];
        rect_position_inverse(2) = yl(2)-rect_position_inverse(2)-rect_position(4)*yl(2);
        text(text_position(1),text_position(2),'\textbf{E}','Units','normalized','FontSize',text_size,'Interpreter','Latex')
        rectangle('Position',rect_position_inverse,'LineWidth',rect_width,'FaceColor','w')
        
        % Zhao ROC E1_3
        subaxis(3,3,8,'Spacing',spacing)
        image(imread('fig5_cropped.jpg'))
        axis image;
        ax = gca;
        ax.XRuler.Axle.Visible = 'off';
        ax.YRuler.Axle.Visible = 'off';
        set(ax,'box','off')
        xl = xlim;
        yl = ylim;
        xticks([0.030 0.218 0.404 0.597 0.783 0.971]*xl(2))
        xticklabels({'0','0.2','0.4','0.6','0.8','1'})
        yticks([0.030 0.218 0.404 0.597 0.783 0.971]*yl(2))
        yticklabels({'1','0.8','0.6','0.4','0.2','0'})
        xlabel('False positive rate','Interpreter','Latex','Units','normalized','FontSize',label_size)
        ylabel('True positive rate','Interpreter','Latex','Units','normalized','FontSize',label_size)
        
        rect_position_inverse = rect_position.*[xl(2),yl(2),xl(2),yl(2)];
        rect_position_inverse(2) = yl(2)-rect_position_inverse(2)-rect_position(4)*yl(2);
        text(text_position(1),text_position(2),'\textbf{H}','Units','normalized','FontSize',text_size,'Interpreter','Latex')
        rectangle('Position',rect_position_inverse,'LineWidth',rect_width,'FaceColor','w')
        
        % E1.1 histograms
        subaxis(3,3,3,'Spacing',spacing)
        % set histogram bins
        histbins = linspace(0,1,50);
        % set ylim
        yl = [0 2500];
        % plot experimental AUC values
        stem(0.502,yl(2),'LineWidth',linewidth_hist,'Color',Dt_colour,'Marker','none')
        hold on
        stem(0.938,yl(2),'LineWidth',linewidth_hist,'Color',f_colour,'Marker','none')
        stem(0.531,yl(2),'LineWidth',linewidth_hist,'Color',Dp_colour,'Marker','none')
        % plot subsampled simulated data
        histogram(results.ROC.E1_1.subsample.AUC(:,2),...
            histbins,'DisplayStyle','stairs','LineWidth',linewidth_hist,'EdgeColor',Dt_colour,'LineStyle',':')
        histogram(results.ROC.E1_1.subsample.AUC(:,1),...
            histbins,'DisplayStyle','stairs','LineWidth',linewidth_hist,'EdgeColor',f_colour,'LineStyle',':')
        histogram(results.ROC.E1_1.subsample.AUC(:,3),...
            histbins,'DisplayStyle','stairs','LineWidth',linewidth_hist,'EdgeColor',Dp_colour,'LineStyle',':')
        % axis settings
        xlim([0,1])
        ylim([0 yl(2)])
        xlabel('AUC value','Interpreter','Latex','Units','normalized','FontSize',label_size)
        ylabel('Count','Interpreter','Latex','Units','normalized','FontSize',label_size)
        % legend
        legend('$AUC_{D_{slow},\:experimental}$','$AUC_{f,\:experimental}$','$AUC_{D_{fast},\:experimental}$',...
            'Location','northwest','FontSize',12, 'Interpreter','Latex')
        text(text_position(1)+0.01,text_position(2),'\textbf{C}','Units','normalized','FontSize',text_size,'Interpreter','Latex')
        rectangle('Position',rect_position.*[1,yl(2),1,yl(2)],'LineWidth',rect_width,'FaceColor','w')
        
        
        % task 2 histograms
        subaxis(3,3,6,'Spacing',spacing)
        % histogram binning
        histbins = linspace(0,1,50);
        % ylim
        yl2 = [0 2500];
        % plot subsampled simulated data
        histogram(results.ROC.E1_2.subsample.AUC(:,2),...
            histbins,'DisplayStyle','stairs','LineWidth',linewidth_hist,'EdgeColor',Dt_colour,'LineStyle',':')
        hold on
        histogram(results.ROC.E1_2.subsample.AUC(:,1),...
            histbins,'DisplayStyle','stairs','LineWidth',linewidth_hist,'EdgeColor',f_colour,'LineStyle',':')
        histogram(results.ROC.E1_2.subsample.AUC(:,3),...
            histbins,'DisplayStyle','stairs','LineWidth',linewidth_hist,'EdgeColor',Dp_colour,'LineStyle',':')
        % plot experimental AUC values
        stem(0.976,yl2(2),'LineWidth',linewidth_hist,'Color',Dt_colour,'Marker','none')
        stem(0.545,yl2(2),'LineWidth',linewidth_hist,'Color',f_colour,'Marker','none')
        stem(0.543,yl2(2),'LineWidth',linewidth_hist,'Color',Dp_colour,'Marker','none','LineStyle','--')
        % axis settings
        xlim([0,1])
        ylim([0 yl2(2)])
        xlabel('AUC value','Interpreter','Latex','Units','normalized','FontSize',label_size)
        ylabel('Count','Interpreter','Latex','Units','normalized','FontSize',label_size)
        text(text_position(1)+0.01,text_position(2),'\textbf{F}','Units','normalized','FontSize',text_size,'Interpreter','Latex')
        rectangle('Position',rect_position.*[1,yl(2),1,yl(2)],'LineWidth',rect_width,'FaceColor','w')
        % legend
        legend('$AUC_{D_{slow},\:simulated}$','$AUC_{f,\:simulated}$','$AUC_{D_{fast},\:simulated}$',...
            'Location','northwest','FontSize',12, 'Interpreter','Latex')
        
        % task 3 histograms
        subaxis(3,3,9,'Spacing',spacing)
        % histogram binning
        histbins = linspace(0,1,50);
        % ylim
        yl = [0 2500];
        % plot subsampled simulated data
        histogram(results.ROC.E1_3.subsample.AUC(:,2),...
            histbins,'DisplayStyle','stairs','LineWidth',linewidth_hist,'EdgeColor',Dt_colour,'LineStyle',':')
        hold on
        histogram(results.ROC.E1_3.subsample.AUC(:,1),...
            histbins,'DisplayStyle','stairs','LineWidth',linewidth_hist,'EdgeColor',f_colour,'LineStyle',':')
        histogram(results.ROC.E1_3.subsample.AUC(:,3),...
            histbins,'DisplayStyle','stairs','LineWidth',linewidth_hist,'EdgeColor',Dp_colour,'LineStyle',':')
        % plot experimental AUC values
        stem(0.983,yl(2),'LineWidth',linewidth_hist,'Color',Dt_colour,'Marker','none')
        stem(0.881,yl(2),'LineWidth',linewidth_hist,'Color',f_colour,'Marker','none')
        stem(0.502,yl(2),'LineWidth',linewidth_hist,'Color',Dp_colour,'Marker','none')
        % axis settings
        xlim([0,1])
        ylim([0 yl(2)])
        xlabel('AUC value','Interpreter','Latex','Units','normalized','FontSize',label_size)
        ylabel('Count','Interpreter','Latex','Units','normalized','FontSize',label_size)
        text(text_position(1)+0.02,text_position(2),'\textbf{I}','Units','normalized','FontSize',text_size,'Interpreter','Latex')
        rectangle('Position',rect_position.*[1,yl(2),1,yl(2)],'LineWidth',rect_width,'FaceColor','w')
        
        set(gcf, 'Color', 'w');
        saveas(gcf,'Figure_2','epsc')
    case 3
        close all
        % spacing between subplots
        spacing = 0.05;
        
        % generate square figure
        figure('units','pixels','outerposition',[0 0 990 380])
        
        % roc linewidth
        linewidth_ROC = 2.5;
        
        %histogram linewidth
        linewidth_hist = 2.5;
        
        % panel label options
        rect_position = [0.02 0.02 0.1 0.1];
        rect_width = 1.5;
        text_position = [0.03,0.06];
        text_size = 18;
        label_size = 12;
        
        % E1.4 simulated ROC curves
        subaxis(1,3,1,'Spacing',spacing)
        % Dslow ROC plot
        plot(results.ROC.E1_4.IVIM.bcNLLS.Dslow.Five.Empirical.x,...
            results.ROC.E1_4.IVIM.bcNLLS.Dslow.Five.Empirical.y,...
            'Color',Dt_colour,'LineWidth',linewidth_ROC,'LineStyle',Dt_style)
        hold on
        % ADC ROC plot
        plot(results.ROC.E1_4.ADC.wLS.ADC.Five.Empirical.x,...
            results.ROC.E1_4.ADC.wLS.ADC.Five.Empirical.y,...
            'Color',ADC_colour,'LineWidth',linewidth_ROC,'LineStyle',adc_style)        
        % x = y line
        fplot(@(x) x,[0 1],'k','LineWidth',linewidth_ROC/2)
        % annotation showing AUC values
        text(0.45,0.18,sprintf('AUC_{D_{slow}} = %.3f \nAUC_{ADC} = %.3f',...
            results.ROC.E1_4.IVIM.bcNLLS.Dslow.Five.Empirical.AUC  ,...
            results.ROC.E1_4.ADC.wLS.ADC.Five.Empirical.AUC),'FontSize',12)
        % set axis settings
        axis equal
        xlim([0 1])
        ylim([0 1])
        xlabel('False positive rate','Interpreter','Latex','Units','normalized','FontSize',label_size)
        ylabel(['\fontsize{15}{0}\selectfont \textbf{E1.4 - Inflamed vs Control}', char(10), ...
            char(10), ...
       '\fontsize{12}{0}\selectfont True positive rate'], ...
       'interpreter','latex','Units','normalized')
        % legend
        legend('$D_{slow}$','$ADC$',...
            'Position',[0.252,0.752,0.055,0.055],...
            'Interpreter','Latex','FontSize',11)
        text(text_position(1),text_position(2),'\textbf{A}','Units','normalized','FontSize',text_size,'Interpreter','Latex')
        rectangle('Position',rect_position,'LineWidth',rect_width,'FaceColor','w')
        
        % Experimental ROC curves
        subaxis(1,3,2,'Spacing',spacing)
        % Dslow ROC plot
        plot(results.ROC.E1_4.IVIM.bcNLLS.Dslow.Clinical.x,...
            results.ROC.E1_4.IVIM.bcNLLS.Dslow.Clinical.y,...
            'Color',Dt_colour,'LineWidth',linewidth_ROC,'LineStyle',Dt_style)
        hold on
        % ADC ROC plot
        plot(results.ROC.E1_4.ADC.wLS.ADC.Clinical.x,...
            results.ROC.E1_4.ADC.wLS.ADC.Clinical.y,...
            'Color',ADC_colour,'LineWidth',linewidth_ROC,'LineStyle',adc_style)        
        % x = y line
        fplot(@(x) x,[0 1],'k','LineWidth',linewidth_ROC/2)
        % annotation showing AUC values
        text(0.45,0.18,sprintf('AUC_{D_{slow}} = %.3f \nAUC_{ADC} = %.3f',...
            results.ROC.E1_4.IVIM.bcNLLS.Dslow.Clinical.AUC  ,...
            results.ROC.E1_4.ADC.wLS.ADC.Clinical.AUC),'FontSize',12)
        % set axis settings
        axis equal
        xlim([0 1])
        ylim([0 1])
        xlabel('False positive rate','Interpreter','Latex','Units','normalized','FontSize',label_size)
        ylabel(['\fontsize{15}{0}\selectfont \textbf{E1.4 - Inflamed vs Control}', char(10), ...
            char(10), ...
       '\fontsize{12}{0}\selectfont True positive rate'], ...
       'interpreter','latex','Units','normalized')
        % legend
        legend('$D_{slow}$','$ADC$',...
            'Position',[0.252,0.752,0.055,0.055],...
            'Interpreter','Latex','FontSize',11)
        text(text_position(1),text_position(2),'\textbf{B}','Units','normalized','FontSize',text_size,'Interpreter','Latex')
        rectangle('Position',rect_position,'LineWidth',rect_width,'FaceColor','w')
        
        % histograms
        subaxis(1,3,3,'Spacing',spacing)
        % set histogram bins
        histbins = linspace(0.5,1,25);
        % set ylim
        yl = [0 2500];
        % plot experimental AUC values
        stem(0.952,yl(2),'LineWidth',linewidth_hist,'Color',Dt_colour,'Marker','none')
        hold on
        stem(0.979,yl(2),'LineWidth',linewidth_hist,'Color',ADC_colour,'Marker','none')
        % plot subsampled simulated data
        histogram(results.ROC.E1_4.subsample.IVIM.AUC,...
            histbins,'DisplayStyle','stairs','LineWidth',linewidth_hist,'EdgeColor',Dt_colour,'LineStyle',':')
        histogram(results.ROC.E1_4.subsample.ADC.AUC,...
            histbins,'DisplayStyle','stairs','LineWidth',linewidth_hist,'EdgeColor',ADC_colour,'LineStyle',':')
        % axis settings
        xlim([0.5,1])
        ylim([0 yl(2)])
        xlabel('AUC value','Interpreter','Latex','Units','normalized','FontSize',label_size)
        ylabel('Count','Interpreter','Latex','Units','normalized','FontSize',label_size)
        % legend
        legend('$AUC_{D_{slow},\:experimental}$','$AUC_{ADC,\:experimental}$','$AUC_{D_{slow},\:simulated}$','$AUC_{ADC,\:simulated}$',...
            'Location','northwest','FontSize',12, 'Interpreter','Latex')
        text(text_position(1)+0.01,text_position(2),'\textbf{C}','Units','normalized','FontSize',text_size,'Interpreter','Latex')
        rectangle('Position',rect_position.*[1,yl(2),1,yl(2)],'LineWidth',rect_width,'FaceColor','w')
        
        set(gcf, 'Color', 'w');
        saveas(gcf,'Figure_3','epsc')
    case 4
        % Generate figure
        figure('units','pixels','outerposition',[0 0 900 1000],'Color', 'w');
        
        % set font sizes for UI elements
        fontsize_master = 12;
        fontsize_legend = 12;
        fontsize_caption = 12;
        fontsize_title = 20;
        linewidth_histogram = 2;
        linewidth_stem = 1.5;
        
        % harmonise histogram properties
        % y axis limit
        max_ylim_ADC = 2500;
        max_ylim_IVIM = 2500;
        % y-axis major ticks
        yticks_ADC = [500 1000 1500 2000 2500];
        yticks_IVIM = yticks_ADC;
        % number of histogram bins
        n_bins = 50;
        % histogram limits
        min_ADC_2_1 = 0;
        max_ADC_2_1 = 1.1;
        min_ADC_2_2 = 0.1;
        max_ADC_2_2 = 1.35;
        min_f_2_1 = 0;
        max_f_2_1 = 0.35;
        min_D_2_2 = 0;
        max_D_2_2 = 1.3;
        % histogram bins
        bins_ADC_2_1 = linspace(min_ADC_2_1,max_ADC_2_1,n_bins);
        bins_f_2_1 = linspace(min_f_2_1,max_f_2_1,n_bins);
        bins_ADC_2_2 = linspace(min_ADC_2_2,max_ADC_2_2,n_bins);
        bins_D_2_2 = linspace(min_D_2_2,max_D_2_2,n_bins);
        
        
        % generate axes
        % E2.1 ROC
        ROC_2_1 = subplot(4,2,[1 3],'FontSize',fontsize_master, 'XGrid','on','YGrid','on');
        % E2.1 ADC
        Hist_2_1_ADC = subplot(4,2,5,'FontSize',fontsize_master, 'XGrid','on','YGrid','on');
        % E2.1 sNLLS
        Hist_2_1_sNLLS = subplot(4,2,7,'FontSize',fontsize_master, 'XGrid','on','YGrid','on');
        % E2.2 ROC
        ROC_2_2 = subplot(4,2,[2 4],'FontSize',fontsize_master, 'XGrid','on','YGrid','on');
        % E2.2 ADC
        Hist_2_2_ADC = subplot(4,2,6,'FontSize',fontsize_master, 'XGrid','on','YGrid','on');
        % E2.2 sNLLS
        Hist_2_2_sNLLS = subplot(4,2,8,'FontSize',fontsize_master, 'XGrid','on','YGrid','on');
        
        % titles
        title(ROC_2_1,'\textbf{E2.1 - Healthy vs. Chronic}','FontSize',fontsize_title,'Interpreter','Latex')
        title(ROC_2_2,'\textbf{E2.2 - Active vs. Chronic}','FontSize',fontsize_title,'Interpreter','Latex')
        title(Hist_2_1_sNLLS,{'';''})
        title(Hist_2_2_sNLLS,{'';''})
        
        % plot data
        % 2.1 ROC
        hold(ROC_2_1,'on')
        plot(ROC_2_1,...
            results.ROC.E2_1.ADC.wLS.ADC.Nine.Synthetic.x,...
            results.ROC.E2_1.ADC.wLS.ADC.Nine.Synthetic.y,...
            'Color',adc_colour,...
            'LineWidth',2.5)
        plot(ROC_2_1,...
            results.ROC.E2_1.IVIM.bcNLLS.f.Nine.Synthetic.x,...
            results.ROC.E2_1.IVIM.bcNLLS.f.Nine.Synthetic.y,...
            'Color',bcnlls_colour,...
            'LineWidth',2.5)
        plot(ROC_2_1,...
            results.ROC.E2_1.IVIM.sNLLS.f.Nine.Synthetic.x,...
            results.ROC.E2_1.IVIM.sNLLS.f.Nine.Synthetic.y,...
            'Color',snlls_colour,...
            'LineWidth',2.5,...
            'LineStyle',':')
        % 2.2 ROC
        hold(ROC_2_2,'on')
        plot(ROC_2_2,...
            results.ROC.E2_2.ADC.wLS.ADC.Nine.Synthetic.x,...
            results.ROC.E2_2.ADC.wLS.ADC.Nine.Synthetic.y,...
            'Color',adc_colour,...
            'LineWidth',2.5)
        plot(ROC_2_2,...
            results.ROC.E2_2.IVIM.bcNLLS.Dslow.Nine.Synthetic.x,...
            results.ROC.E2_2.IVIM.bcNLLS.Dslow.Nine.Synthetic.y,...
            'Color',bcnlls_colour,...
            'LineWidth',2.5)
        plot(ROC_2_2,...
            results.ROC.E2_2.IVIM.sNLLS.Dslow.Nine.Synthetic.x,...
            results.ROC.E2_2.IVIM.sNLLS.Dslow.Nine.Synthetic.y,...
            'Color',snlls_colour,...
            'LineWidth',2.5,...
            'LineStyle',':')
        % 2.1 histograms, ADC
        hold(Hist_2_1_ADC,'on')
        histogram(Hist_2_1_ADC,...
            results.Healthy.Nine.Synthetic.ADC.wLS.parameters(2,:),...
            bins_ADC_2_1,...
            'DisplayStyle','stairs',...
            'LineWidth',linewidth_histogram,...
            'EdgeColor',adc_colour,...
            'LineStyle',':')
        histogram(Hist_2_1_ADC,...
            results.Chronic_1.Nine.Synthetic.ADC.wLS.parameters(2,:),...
            bins_ADC_2_1,...
            'DisplayStyle','stairs',...
            'LineWidth',linewidth_histogram,...
            'EdgeColor',adc_colour)
        % ground truth D_IVIM, same for healthy and chronic
        stem(Hist_2_1_ADC,...
            tissue.Chronic_1.params.mu(3),...
            max_ylim_ADC,...
            'LineStyle','-',...
            'LineWidth',linewidth_stem,...
            'Color','k',...
            'Marker','none')
        % 2.1 histograms, sNLLS
        hold(Hist_2_1_sNLLS,'on')
        histogram(Hist_2_1_sNLLS,...
            results.Healthy.Nine.Synthetic.IVIM.sNLLS.parameters(2,:),...
            bins_f_2_1,...
            'DisplayStyle','stairs',...
            'LineWidth',linewidth_histogram,...
            'EdgeColor',snlls_colour,...
            'LineStyle',':')
        histogram(Hist_2_1_sNLLS,...
            results.Chronic_1.Nine.Synthetic.IVIM.sNLLS.parameters(2,:),...
            bins_f_2_1,...
            'DisplayStyle','stairs',...
            'LineWidth',linewidth_histogram,...
            'EdgeColor',snlls_colour)
        % ground truth f
        stem(Hist_2_1_sNLLS,...
            tissue.Healthy.params.mu(2),...
            max_ylim_ADC,...
            'LineStyle','--',...
            'LineWidth',linewidth_stem,...
            'Color','k',...
            'Marker','none')
        stem(Hist_2_1_sNLLS,...
            tissue.Chronic_1.params.mu(2),...
            max_ylim_ADC,...
            'LineStyle','-',...
            'LineWidth',linewidth_stem,...
            'Color','k',...
            'Marker','none')
        % 2.2 histograms, ADC
        hold(Hist_2_2_ADC,'on')
        histogram(Hist_2_2_ADC,...
            results.Active.Nine.Synthetic.ADC.wLS.parameters(2,:),...
            bins_ADC_2_2,...
            'DisplayStyle','stairs',...
            'LineWidth',linewidth_histogram,...
            'EdgeColor',adc_colour,...
            'LineStyle',':')
        histogram(Hist_2_2_ADC,...
            results.Chronic_2.Nine.Synthetic.ADC.wLS.parameters(2,:),...
            bins_ADC_2_2,...
            'DisplayStyle','stairs',...
            'LineWidth',linewidth_histogram,...
            'EdgeColor',adc_colour)
        % ground truth D_IVIM
        stem(Hist_2_2_ADC,...
            tissue.Active.params.mu(3),...
            max_ylim_ADC,...
            'LineStyle','--',...
            'LineWidth',linewidth_stem,...
            'Color','k',...
            'Marker','none')
        stem(Hist_2_2_ADC,...
            tissue.Chronic_2.params.mu(3),...
            max_ylim_ADC,...
            'LineStyle','-',...
            'LineWidth',linewidth_stem,...
            'Color','k',...
            'Marker','none')
        % 2.2 histograms, sNLLS
        hold(Hist_2_2_sNLLS,'on')
        histogram(Hist_2_2_sNLLS,...
            results.Active.Nine.Synthetic.IVIM.sNLLS.parameters(3,:),...
            bins_D_2_2,...
            'DisplayStyle','stairs',...
            'LineWidth',linewidth_histogram,...
            'EdgeColor',snlls_colour,...
            'LineStyle',':')
        histogram(Hist_2_2_sNLLS,...
            results.Chronic_2.Nine.Synthetic.IVIM.sNLLS.parameters(3,:),...
            bins_D_2_2,...
            'DisplayStyle','stairs',...
            'LineWidth',linewidth_histogram,...
            'EdgeColor',snlls_colour)
        % ground truth D
        stem(Hist_2_2_sNLLS,...
            tissue.Active.params.mu(3),...
            max_ylim_IVIM,...
            'LineStyle','--',...
            'LineWidth',linewidth_stem,...
            'Color','k',...
            'Marker','none')
        stem(Hist_2_2_sNLLS,...
            tissue.Chronic_2.params.mu(3),...
            max_ylim_IVIM,...
            'LineStyle','-',...
            'LineWidth',linewidth_stem,...
            'Color','k',...
            'Marker','none')
        
        % captions
        % 2.1 ROC
        text(ROC_2_1,...
            0.26,0.2,...
            sprintf('AUC_{ADC} = %.3f \nAUC_{IVIM, bcNLLS} = %.3f \nAUC_{IVIM, sNLLS} = %.3f',...
            results.ROC.E2_1.ADC.wLS.ADC.Nine.Synthetic.AUC,...
            results.ROC.E2_1.IVIM.bcNLLS.f.Nine.Synthetic.AUC,...
            results.ROC.E2_1.IVIM.sNLLS.f.Nine.Synthetic.AUC), 'Fontsize',fontsize_caption)
        % 2.2 ROC
        text(ROC_2_2,...
            0.26,0.2,...
            sprintf('AUC_{ADC} = %.3f \nAUC_{IVIM, bcNLLS} = %.3f \nAUC_{IVIM, sNLLS} = %.3f',...
            results.ROC.E2_2.ADC.wLS.ADC.Nine.Synthetic.AUC,...
            results.ROC.E2_2.IVIM.bcNLLS.Dslow.Nine.Synthetic.AUC,...
            results.ROC.E2_2.IVIM.sNLLS.Dslow.Nine.Synthetic.AUC), 'Fontsize',fontsize_caption)
        % 2.1 ADC histogram
        text(Hist_2_1_ADC,...
            (max_ADC_2_1+min_ADC_2_1)/2 + (max_ADC_2_1-min_ADC_2_1)*0.2,...
            max_ylim_ADC*0.5,...
            sprintf('CNR = %.2f \n\\Delta\\mu = %.3f \n\\sigma_{healthy} = %.3f \n\\sigma_{chronic} = %.3f',...
            results.CNR.E2_1.ADC.wLS.ADC.CNR, ...
            results.CNR.E2_1.ADC.wLS.ADC.delta_mu,...
            results.CNR.E2_1.ADC.wLS.ADC.sigma.Healthy,...
            results.CNR.E2_1.ADC.wLS.ADC.sigma.Chronic_1),...
            'FontSize',fontsize_legend)
        % 2.1 sNLLS histogram
        text(Hist_2_1_sNLLS,...
            (max_f_2_1+min_f_2_1)/2 + (max_f_2_1-min_f_2_1)*0.2,...
            max_ylim_IVIM*0.5,...
            sprintf('CNR = %.2f \n\\Delta\\mu = %.3f \n\\sigma_{healthy} = %.3f \n\\sigma_{chronic} = %.3f',...
            results.CNR.E2_1.IVIM.sNLLS.f.CNR,...
            results.CNR.E2_1.IVIM.sNLLS.f.delta_mu,...
            results.CNR.E2_1.IVIM.sNLLS.f.sigma.Healthy,...
            results.CNR.E2_1.IVIM.sNLLS.f.sigma.Chronic_1),...
            'FontSize',fontsize_legend)
        % 2.2 ADC histogram
        text(Hist_2_2_ADC,...
            (max_ADC_2_2+min_ADC_2_2)/2 + (max_ADC_2_2-min_ADC_2_2)*0.2,...
            max_ylim_ADC*0.5,...
            sprintf('CNR = %.2f \n\\Delta\\mu = %.3f \n\\sigma_{active} = %.3f \n\\sigma_{chronic} = %.3f',...
            results.CNR.E2_2.ADC.wLS.ADC.CNR, ...
            results.CNR.E2_2.ADC.wLS.ADC.delta_mu,...
            results.CNR.E2_2.ADC.wLS.ADC.sigma.Active,...
            results.CNR.E2_2.ADC.wLS.ADC.sigma.Chronic_2),...
            'FontSize',fontsize_legend)
        % 2.2 sNLLS histogram
        text(Hist_2_2_sNLLS,...
            (max_D_2_2+min_D_2_2)/2 + (max_D_2_2-min_D_2_2)*0.2,...
            max_ylim_IVIM*0.5,...
            sprintf('CNR = %.2f \n\\Delta\\mu = %.3f \n\\sigma_{active} = %.3f \n\\sigma_{chronic} = %.3f',...
            results.CNR.E2_2.IVIM.sNLLS.Dslow.CNR,...
            results.CNR.E2_2.IVIM.sNLLS.Dslow.delta_mu,...
            results.CNR.E2_2.IVIM.sNLLS.Dslow.sigma.Active,...
            results.CNR.E2_2.IVIM.sNLLS.Dslow.sigma.Chronic_2),...
            'FontSize',fontsize_legend)
        
        
        % axis labels
        xlabel(ROC_2_1,'False positive rate','Interpreter','Latex')
        ylabel(ROC_2_1,'True positive rate','Interpreter','Latex')
        xlabel(ROC_2_2,'False positive rate','Interpreter','Latex')
        ylabel(ROC_2_2,'True positive rate','Interpreter','Latex')
        xlabel(Hist_2_1_ADC,sprintf('$$\\widehat{ADC}$$\n'),'Interpreter','Latex')
        xlabel(Hist_2_2_ADC,sprintf('$$\\widehat{ADC}$$\n'),'Interpreter','Latex')
        xlabel(Hist_2_1_sNLLS,sprintf('$$\\widehat{f}$$\n'),'Interpreter','Latex')
        xlabel(Hist_2_2_sNLLS,sprintf('$$\\widehat{D_{slow}}$$\n'),'Interpreter','Latex')
        
        % axis data aspect ratios
        axis(ROC_2_1,'equal')
        axis(ROC_2_2,'equal')
        
        % axis limits
        set(ROC_2_1,'XLim',[0 1],'YLim',[0 1])
        set(ROC_2_2,'XLim',[0 1],'YLim',[0 1])
        set(Hist_2_1_ADC,'XLim',[min_ADC_2_1 max_ADC_2_1],'YLim',[0 max_ylim_ADC])
        set(Hist_2_2_ADC,'XLim',[min_ADC_2_2 max_ADC_2_2],'YLim',[0 max_ylim_ADC])
        set(Hist_2_1_sNLLS,'XLim',[min_f_2_1 max_f_2_1],'YLim',[0 max_ylim_IVIM])
        set(Hist_2_2_sNLLS,'XLim',[min_D_2_2 max_D_2_2],'YLim',[0 max_ylim_IVIM])
        
        % legends
        legend(ROC_2_1,'ADC','bcNLLS','sNLLS','Location','northwest','Interpreter','Latex')
        legend(ROC_2_2,'ADC','bcNLLS','sNLLS','Location','northwest','Interpreter','Latex')
        legend(Hist_2_1_ADC,'$\widehat{ADC}_{healthy}$',...
            '$\widehat{ADC}_{chronic}$',...
            '$D_{IVIM}$ groundtruth',...
            'Interpreter','Latex','FontSize',fontsize_legend,'NumColumns',2,'Position',...
            [0.15489363229636,0.264543029954841,0.269550819396973,0.040398198023163]);
        legend(Hist_2_1_sNLLS,'$\widehat{f}_{healthy}$',...
            '$\widehat{f}_{chronic}$',...
            '$f_{healthy}$ groundtruth','$f_{chronic}$ groundtruth',...
            'Interpreter','Latex','FontSize',fontsize_legend,'NumColumns',2,'Position',...
            [0.167973259650336,0.038492508143322,0.243697925143772,0.042214983713355]);
        legend(Hist_2_2_ADC,'$\widehat{ADC}_{active}$',...
            '$\widehat{ADC}_{chronic}$',...
            '$D_{slow, active}$ groundtruth',...
            '$D_{slow, chronic}$ groundtruth',...
            'Interpreter','Latex','FontSize',fontsize_legend,'NumColumns',2,'Position',...
            [0.598226965629693,0.263424513071464,0.269550819396973,0.042635231789918]);
        legend(Hist_2_2_sNLLS,'$\widehat{D}_{slow, active}$',...
            '$\widehat{D}_{slow, chronic}$',...
            '$D_{slow, active}$ groundtruth','$D_{slow, chronic}$ groundtruth',...
            'Interpreter','Latex','FontSize',fontsize_legend,'NumColumns',2,'Position',...
            [0.602169615258111,0.038492508143322,0.277527436150445,0.042214983713355]);
        
        saveas(gcf,'Figure_4','epsc')
    case 5
        close all
        figure('units','pixels','outerposition',[0 0 1200 900],'Color', 'w');        
        
        % set font sizes for UI elements
        fontsize_master = 16;
        fontsize_legend = 14;
        fontsize_caption = 14;
        fontsize_title = 20;
        linewidth_histogram = 2;
        linewidth_stem = 1.5;
        
        spacing = 0.05;
        
        max_ylim = 3000;
        
        % generate histogram limits
        hist_num = 50;
        
        max_f = 0.35;
        min_f = 0;
        histlims_f = linspace(min_f,max_f,hist_num);
        
        max_D = 1.3;
        min_D = 0;
        histlims_D = linspace(min_D,max_D,hist_num);
        
        % histograms E2.1
        subaxis(3,4,[1 2 5 6],'Spacing',spacing)
        set(gca,'FontSize',fontsize_master)
        histogram(results.Chronic_1.Nine.Synthetic.IVIM.sNLLS.parameters(2,:),...
            histlims_f,...
            'DisplayStyle','stairs',...
            'LineWidth',linewidth_histogram,...
            'EdgeColor',snlls_colour)
        hold on
        histogram(results.Chronic_1.Nine.Synthetic.IVIM.bcNLLS.parameters(2,:),...
            histlims_f,...
            'DisplayStyle','stairs',...
            'LineWidth',linewidth_histogram,...
            'EdgeColor',bcnlls_colour)
        histogram(results.Healthy.Nine.Synthetic.IVIM.sNLLS.parameters(2,:),...
            histlims_f,...
            'DisplayStyle','stairs',...
            'LineWidth',linewidth_histogram,...
            'EdgeColor',snlls_colour,...
            'LineStyle',':')
        histogram(results.Healthy.Nine.Synthetic.IVIM.bcNLLS.parameters(2,:),...
            histlims_f,...
            'DisplayStyle','stairs',...
            'LineWidth',linewidth_histogram,...
            'EdgeColor',bcnlls_colour,...
            'LineStyle',':')                
        stem(tissue.Healthy.params.mu(2),max_ylim,'LineStyle','--','LineWidth',linewidth_stem,'Color','k','Marker','none')
        stem(tissue.Chronic_1.params.mu(2),max_ylim,'LineWidth',linewidth_stem,'Color','k','Marker','none')
        
        ylim([0 max_ylim]);
        xlim([min_f, max_f])
        grid on
        yticks([0 500 1000 1500 2000 2500 3000])
        
        xlabel('$$\widehat{f}$$','Interpreter','Latex','FontSize',fontsize_master)
        
        caption  = sprintf('CNR_{sNLLS} = %.2f \nCNR_{bcNLLS} = %.2f \n\n\\Delta\\mu_{sNLLS} = %.3f \n\\Delta\\mu_{bcNLLS} = %.3f \n\n\\sigma_{healthy,sNLLS} = %.3f \n\\sigma_{chronic,sNLLS} = %.3f \n\n\\sigma_{healthy,bcNLLS} = %.3f \n\\sigma_{chronic,bcNLLS} = %.3f',...
            results.CNR.E2_1.IVIM.sNLLS.f.CNR, ...
            results.CNR.E2_1.IVIM.bcNLLS.f.CNR, ...
            results.CNR.E2_1.IVIM.sNLLS.f.delta_mu,...
            results.CNR.E2_1.IVIM.bcNLLS.f.delta_mu,...
            results.CNR.E2_1.IVIM.sNLLS.f.sigma.Healthy,...
            results.CNR.E2_1.IVIM.sNLLS.f.sigma.Chronic_1,...
            results.CNR.E2_1.IVIM.bcNLLS.f.sigma.Healthy,...
            results.CNR.E2_1.IVIM.bcNLLS.f.sigma.Chronic_1);
        
        text((max_f+min_f)/2 + (max_f-min_f)*0.12,max_ylim*0.63,caption,'FontSize',fontsize_caption)
        
        legend('$\widehat{f}_{healthy,sNLLS}$',...
            '$\widehat{f}_{chronic,sNLLS}$',...
            '$\widehat{f}_{healthy,bcNLLS}$',...
            '$\widehat{f}_{chronic,bcNLLS}$',...
            '$f_{healthy}$',...
            '$f_{chronic}$',...
            'Interpreter','Latex','Location','northwest','FontSize',fontsize_legend)
        title('\textbf{E2.1 - Healthy vs. Chronic}','FontSize',fontsize_title,'Interpreter','Latex')
        
        % histograms E2.2
        subaxis(3,4,[3 4 7 8],'Spacing',spacing)
        set(gca,'FontSize',fontsize_master)
        
        histogram(results.Chronic_2.Nine.Synthetic.IVIM.sNLLS.parameters(3,:),...
            histlims_D,...
            'DisplayStyle','stairs',...
            'LineWidth',linewidth_histogram,...
            'EdgeColor',snlls_colour)
        hold on
        histogram(results.Chronic_2.Nine.Synthetic.IVIM.bcNLLS.parameters(3,:),...
            histlims_D,...
            'DisplayStyle','stairs',...
            'LineWidth',linewidth_histogram,...
            'EdgeColor',bcnlls_colour)
        histogram(results.Active.Nine.Synthetic.IVIM.sNLLS.parameters(3,:),...
            histlims_D,...
            'DisplayStyle','stairs',...
            'LineWidth',linewidth_histogram,...
            'EdgeColor',snlls_colour,...
            'LineStyle',':')
        histogram(results.Active.Nine.Synthetic.IVIM.bcNLLS.parameters(3,:),...
            histlims_D,...
            'DisplayStyle','stairs',...
            'LineWidth',linewidth_histogram,...
            'EdgeColor',bcnlls_colour,...
            'LineStyle',':')                
        stem(tissue.Active.params.mu(3),max_ylim,'LineStyle','--','LineWidth',linewidth_stem,'Color','k','Marker','none')
        stem(tissue.Chronic_2.params.mu(3),max_ylim,'LineWidth',linewidth_stem,'Color','k','Marker','none')
        
        ylim([0 max_ylim]);
        xlim([min_D, max_D])
        grid on
        yticks([0 500 1000 1500 2000 2500 3000])
        
        xlabel('$$\widehat{D_{slow}}$$','Interpreter','Latex','FontSize',fontsize_master)
        
        caption  = sprintf('CNR_{sNLLS} = %.2f \nCNR_{bcNLLS} = %.2f \n\n\\Delta\\mu_{sNLLS} = %.3f \n\\Delta\\mu_{bcNLLS} = %.3f \n\n\\sigma_{active,sNLLS} = %.3f \n\\sigma_{chronic,sNLLS} = %.3f \n\n\\sigma_{active,bcNLLS} = %.3f \n\\sigma_{chronic,bcNLLS} = %.3f',...
            results.CNR.E2_2.IVIM.sNLLS.Dslow.CNR, ...
            results.CNR.E2_2.IVIM.bcNLLS.Dslow.CNR, ...
            results.CNR.E2_2.IVIM.sNLLS.Dslow.delta_mu,...
            results.CNR.E2_2.IVIM.bcNLLS.Dslow.delta_mu,...
            results.CNR.E2_2.IVIM.sNLLS.Dslow.sigma.Active,...
            results.CNR.E2_2.IVIM.sNLLS.Dslow.sigma.Chronic_2,...
            results.CNR.E2_2.IVIM.bcNLLS.Dslow.sigma.Active,...
            results.CNR.E2_2.IVIM.bcNLLS.Dslow.sigma.Chronic_2);
        
        text((max_D+min_D)/2 + (max_D-min_D)*0.12,max_ylim*0.63,caption,'FontSize',fontsize_caption)
        
        legend('$\widehat{D_{slow}}_{, active, sNLLS}$',...
            '$\widehat{D_{slow}}_{, chronic,sNLLS}$',...
            '$\widehat{D_{slow}}_{, active,bcNLLS}$',...
            '$\widehat{D_{slow}}_{, chronic,bcNLLS}$',...
            '$D_{slow, active}$',...
            '$D_{slow, chronic}$',...
            'Interpreter','Latex','Location','northwest','FontSize',fontsize_legend)
        title('\textbf{E2.2 - Active vs. Chronic}','FontSize',fontsize_title,'Interpreter','Latex')
        
        % E2.1 density plots
        subaxis(3,4,9,'Spacing',spacing)
        set(gca,'FontSize',fontsize_master)
        fplot(@(x) x,'r','LineWidth',2)
        hold on
        dscatter(results.Healthy.Nine.Synthetic.IVIM.sNLLS.parameters(2,:)',...
            results.Healthy.Nine.Synthetic.IVIM.bcNLLS.parameters(2,:)')
        fplot(@(x) x,'r','LineWidth',2)
        legend('Equality','Location','southeast','FontSize',fontsize_legend,'Interpreter','Latex')
        axis equal
        xlim([0 0.35])
        ylim([0 0.35])
        grid on
        yticks([0.1 0.2 0.3])
        xlabel('$\widehat{f}_{healthy,sNLLS}$','Interpreter','Latex','FontSize',fontsize_master)
        ylabel('$\widehat{f}_{healthy,bcNLLS}$','Interpreter','Latex','FontSize',fontsize_master)
        
        subaxis(3,4,10,'Spacing',spacing)
        set(gca,'FontSize',fontsize_master)
        fplot(@(x) x,'r','LineWidth',2)
        hold on
        dscatter(results.Chronic_1.Nine.Synthetic.IVIM.sNLLS.parameters(2,:)',...
            results.Chronic_1.Nine.Synthetic.IVIM.bcNLLS.parameters(2,:)')
        fplot(@(x) x,'r','LineWidth',2)
        legend('Equality','Location','southeast','FontSize',fontsize_legend,'Interpreter','Latex')
        axis equal
        xlim([0 0.35])
        ylim([0 0.35])
        grid on
        yticks([0.1 0.2 0.3])
        xlabel('$\widehat{f}_{chronic,sNLLS}$','Interpreter','Latex','FontSize',fontsize_master)
        ylabel('$\widehat{f}_{chronic,bcNLLS}$','Interpreter','Latex','FontSize',fontsize_master)
        
        % E2.2 density plots
        subaxis(3,4,11,'Spacing',spacing)
        set(gca,'FontSize',fontsize_master)
        fplot(@(x) x,'r','LineWidth',2)
        hold on
        dscatter(results.Active.Nine.Synthetic.IVIM.sNLLS.parameters(3,:)',...
            results.Active.Nine.Synthetic.IVIM.bcNLLS.parameters(3,:)')
        fplot(@(x) x,'r','LineWidth',2)
        legend('Equality','Location','northwest','FontSize',fontsize_legend,'Interpreter','Latex')
        axis equal
        xlim([0 1.2])
        ylim([0 1.2])
        grid on
        yticks([0 0.5 1.0])
        xlabel('$\widehat{D}_{slow,active,sNLLS}$','Interpreter','Latex','FontSize',fontsize_master)
        ylabel('$\widehat{D}_{slow,active,bcNLLS}$','Interpreter','Latex','FontSize',fontsize_master)
        
        subaxis(3,4,12,'Spacing',spacing)
        set(gca,'FontSize',fontsize_master)
        fplot(@(x) x,'r','LineWidth',2)
        hold on
        dscatter(results.Chronic_2.Nine.Synthetic.IVIM.sNLLS.parameters(3,:)',...
            results.Chronic_2.Nine.Synthetic.IVIM.bcNLLS.parameters(3,:)')
        fplot(@(x) x,'r','LineWidth',2)
        legend('Equality','Location','northwest','FontSize',fontsize_legend,'Interpreter','Latex')
        axis equal
        xlim([0 1.2])
        ylim([0 1.2])
        grid on
        yticks([0 0.5 1])
        xlabel('$\widehat{D}_{slow, chronic,sNLLS}$','Interpreter','Latex','FontSize',fontsize_master)
        ylabel('$\widehat{D}_{slow, chronic,bcNLLS}$','Interpreter','Latex','FontSize',fontsize_master)
        
        saveas(gcf,'Figure_5','epsc')
end




end